import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

//  Load font tuỳ chỉnh Geist Sans
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

//  Load font tuỳ chỉnh Geist Mono
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

//  Metadata cho toàn bộ website (SEO)
export const metadata: Metadata = {
  title: "Chatbot Du lịch Việt Nam",
  description: "Generated by create next app",
};

//  Root Layout – layout gốc cho toàn bộ ứng dụng
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // 🌐 HTML skeleton
    <html lang="en">
      {/* 
         Gán biến font vào <body>
        → Giúp sử dụng font Geist trên toàn website
      */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* 
           ClerkProvider: Provider cho tính năng Auth (login, signup)
          → Giúp các trang con có thể dùng useUser(), <UserButton />, ...
        */}
        <ClerkProvider>
          {/* Thanh header (hiện đang trống) */}
          <header></header>

          {/* Nội dung chính của toàn bộ app */}
          <main>{children}</main>
        </ClerkProvider>
      </body>
    </html>
  );
}
